export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';

export const WEATHERDATA_LOADING = 'WEATHERDATA_LOADING';
export const WEATHERDATA_SUCCESS = 'WEATHERDATA_SUCCESS';
export const WEATHERDATA_FAILURE = 'WEATHERDATA_FAILURE';
